<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Mengajar;

class MengajarSeeder extends Seeder
{
    public static function run()
    {
        Mengajar::insert([
            ['mataKuliah_id' => '1', 'dosen_id' => '24', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '1', 'dosen_id' => '24', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '2', 'dosen_id' => '21', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '2', 'dosen_id' => '21', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '5', 'dosen_id' => '22', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '5', 'dosen_id' => '22', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '6', 'dosen_id' => '16', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '6', 'dosen_id' => '16', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '7', 'dosen_id' => '23', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '7', 'dosen_id' => '23', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '8', 'dosen_id' => '30', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '8', 'dosen_id' => '8', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '9', 'dosen_id' => '30', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '9', 'dosen_id' => '8', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '10', 'dosen_id' => '4', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '10', 'dosen_id' => '1', 'prodi' => 'D3', 'semester' => '1', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '11', 'dosen_id' => '14', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '11', 'dosen_id' => '14', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '13', 'dosen_id' => '23', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '13', 'dosen_id' => '20', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '14', 'dosen_id' => '4', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '14', 'dosen_id' => '4', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '15', 'dosen_id' => '12', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '15', 'dosen_id' => '12', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '16', 'dosen_id' => '18', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '16', 'dosen_id' => '28', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '17', 'dosen_id' => '6', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '17', 'dosen_id' => '9', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '18', 'dosen_id' => '4', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '18', 'dosen_id' => '4', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '19', 'dosen_id' => '12', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '19', 'dosen_id' => '12', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '20', 'dosen_id' => '18', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '20', 'dosen_id' => '28', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '21', 'dosen_id' => '6', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '21', 'dosen_id' => '9', 'prodi' => 'D3', 'semester' => '2', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '22', 'dosen_id' => '14', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '22', 'dosen_id' => '14', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '24', 'dosen_id' => '5', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '24', 'dosen_id' => '20', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '25', 'dosen_id' => '6', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '25', 'dosen_id' => '10', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '26', 'dosen_id' => '17', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '26', 'dosen_id' => '17', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '27', 'dosen_id' => '25', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '27', 'dosen_id' => '28', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '28', 'dosen_id' => '6', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '28', 'dosen_id' => '10', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '29', 'dosen_id' => '12', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '29', 'dosen_id' => '12', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '30', 'dosen_id' => '25', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '30', 'dosen_id' => '28', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '31', 'dosen_id' => '4', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '31', 'dosen_id' => '6', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '32', 'dosen_id' => '28', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '32', 'dosen_id' => '18', 'prodi' => 'D3', 'semester' => '3', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '34', 'dosen_id' => '18', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '34', 'dosen_id' => '18', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '35', 'dosen_id' => '10', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '35', 'dosen_id' => '29', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '36', 'dosen_id' => '5', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '36', 'dosen_id' => '27', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '37', 'dosen_id' => '14', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '37', 'dosen_id' => '14', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '38', 'dosen_id' => '25', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '38', 'dosen_id' => '25', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '39', 'dosen_id' => '17', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '39', 'dosen_id' => '17', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '40', 'dosen_id' => '5', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '40', 'dosen_id' => '27', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '41', 'dosen_id' => '9', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '41', 'dosen_id' => '30', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '42', 'dosen_id' => '1', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '42', 'dosen_id' => '1', 'prodi' => 'D3', 'semester' => '4', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '43', 'dosen_id' => '26', 'prodi' => 'D3', 'semester' => '5', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '43', 'dosen_id' => '26', 'prodi' => 'D3', 'semester' => '5', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '44', 'dosen_id' => '23', 'prodi' => 'D3', 'semester' => '5', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '44', 'dosen_id' => '23', 'prodi' => 'D3', 'semester' => '5', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '45', 'dosen_id' => '3', 'prodi' => 'D3', 'semester' => '5', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '45', 'dosen_id' => '5', 'prodi' => 'D3', 'semester' => '5', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '46', 'dosen_id' => '29', 'prodi' => 'D3', 'semester' => '5', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '46', 'dosen_id' => '29', 'prodi' => 'D3', 'semester' => '5', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '49', 'dosen_id' => '26', 'prodi' => 'D3', 'semester' => '6', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '49', 'dosen_id' => '26', 'prodi' => 'D3', 'semester' => '6', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '51', 'dosen_id' => '5', 'prodi' => 'D3', 'semester' => '6', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '51', 'dosen_id' => '3', 'prodi' => 'D3', 'semester' => '6', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '52', 'dosen_id' => '11', 'prodi' => 'D3', 'semester' => '6', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '52', 'dosen_id' => '11', 'prodi' => 'D3', 'semester' => '6', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '53', 'dosen_id' => '23', 'prodi' => 'D3', 'semester' => '6', 'kelas' => 'A', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['mataKuliah_id' => '53', 'dosen_id' => '23', 'prodi' => 'D3', 'semester' => '6', 'kelas' => 'B', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')]
        ]);
    }
}
